### ISSUE TITLE
No VAAPI Intel GPU Acceleration

### ISSUE THREAD

**Issue by DocMAX** [ehough/docker-kodi#17] opened 2019-02-09 11:22 UTC
I don't get gpu acceleration working. I have an Intel GPU which supports x264 hardware decoding. Is there maybe another package missing for this?

I see an error after start:

`Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory`

**Comment by DocMAX** [comment] 2019-02-09 12:22
Next: I installed apt install libvdpau_va_gl1 package. Getting this now:

```
---> starting Kodi with command: kodi-standalone
Failure: Module initialization failed
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
Segmentation fault (core dumped)

```

**Comment by ehough** [comment] 2019-02-11 21:28
Post a list of packages installed on your host to [pastebin](https://pastebin.com/)? i.e.g `dpkg -l`

I'll compare it to packages installed on my system, which also has an Intel GPU, to see if I can see anything missing.

**Comment by ehough** [comment] 2019-02-14 19:40
@DocMAX were you able to make any progress on this? Just checking in to see if there's anything I can do from my end to help.

**Comment by mviereck** [comment] 2019-02-17 23:01
Maybe try to run with `--privileged` to check if it makes a difference. Not recommended as a solution, though.
```
x11docker   --xorg                                 \
            --vt 7                                 \
            --pulseaudio                           \
            --wm none                              \                
            --gpu                                  \
            --homedir /host/path/to/kodi/home      \
            -- \
            -v /host/path/to/media:/media:ro    \
            --privileged      \ 
            -- \
            erichough/kodi

**Comment by ehough** [comment] 2019-02-19 17:55
In addition to @mviereck's idea, you might also want to make sure that you have the `i965-va-driver` package installed on the host.

Closing this issue for inactivity but feel free to re-open or continue the discussion!

**Comment by begicj** [comment] 2019-04-16 20:28
I had the same problems with hardware acceleration on Intel N3050. All drivers are installed on the host (debian 9) and the hardware acceleration of the applications on the host is working normally. Here is log:

 .............erichough-kodi-88b82c/share/stderr <==
libva info: VA-API version 1.1.0
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: va_openDriver() returns -1
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory

The issue was fixed by adding:

apt-get upgrade -y        && \
apt-get install -y i965-va-driver mesa-utils mesa-utils-extra libxv1      && \

to Dockerfile and building a new docker image with the included drivers.

**Comment by ehough** [comment] 2019-04-16 20:38
@begicj Thank you for the report. Could you let us know which version of x11docker you're using? I'd like to try to reproduce this issue locally and investigate further.

**Comment by begicj** [comment] 2019-04-16 20:54
x11docker version 5.5.2

**Comment by mviereck** [comment] 2019-04-16 22:29
@begicj  Thank you for reporting this!

@ehough I had a look at these packages. I'd recommend to install `va-driver-all` instead of `i965-va-driver` to get the drivers for AMD and Nvidia, too.

I have updated the x11docker image  dependency list accordingly: https://github.com/mviereck/x11docker/wiki/Dependencies#dependencies-in-image

**Comment by ehough** [comment] 2019-05-06 20:39
> I had a look at these packages. I'd recommend to install va-driver-all instead of i965-va-driver to get the drivers for AMD and Nvidia, too.
>
> I have updated the x11docker image dependency list accordingly: https://github.com/mviereck/x11docker/wiki/Dependencies#dependencies-in-image

I've been hesitant to add those packages to the image because of some recent testing. What's weird is that in my personal HTPC, which uses Intel graphics, I get normal hardware-accelerated video *without* the `va-driver-all` or `i965-va-driver` packages. In other words, the current version of `erichough/kodi` works fine and the error messages (reported above) appear to be harmless.

I'm going to do some more testing tonight and will report back. Stand by!

**Comment by mviereck** [comment] 2019-05-06 20:43
From what I understand, these drivers help to _decode_ videos with the GPU.
_Displaying_ the video is already accelerated with the help of the MESA drivers.

**Comment by wsw70** [comment] 2019-05-08 04:23
Adding `--priviledged` fixed the issue

**Comment by maps2002** [comment] 2020-01-05 00:29
Hi,
I also have this error.
I was able to clear it after creating a new image that installs va-driver-all and libxv1.
Thank you.

**Comment by lulol** [comment] 2020-08-31 11:36
@ehough  With Linux Mint 20 using Intel graphics, I only get SW decoded x264 video as reported by kodi in the latest version of `erichough/kodi` and  x11docker --version 6.6.2

Although have been planning to migrate my HTPC to CentOS don't know if that would make any difference.

Since the `--privileged` flag didn't help, as a test attempted to update the packages `i965-va-driver` `mesa-utils` `mesa-utils-extra` `libxv1` mentioned by @begicj , from within the container with:

```
$ docker -it x11docker_X101_erichough-kodi_71114237194 /bin/bash
# apt-get install i965-va-driver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package i965-va-driver is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'i965-va-driver' has no installation candidate
```
same with `va-driver-all`  and the rest of packages.

So the only solution for now to get HW decoded video for my setup is to recreate the container adding these packages?

I've very little experience with docker and I'm not sure if that would mean recreating it manually with each update or to get stuck with an old image.

Thank you.

**Comment by gsantner** [comment] 2020-08-31 11:40
have you seen the `--gpu` option as well, aside `--priviledged`

**Comment by lulol** [comment] 2020-08-31 12:54
> @gsantner have you seen the `--gpu` option as well, aside `--priviledged`

I used this with and without the `--privileged` (spelling!) flag as shown in the @mviereck example and have added the `--name` option. (Must use sudo because otherwise fails to start for non console users)

```
sudo x11docker  --name kodi \
            --xorg     \
            --vt 8 \
            --wm=none \
            --pulseaudio                           \
            --gpu                                  \
            --home=/home/luis/docker/kodi      \
            -- \
              -v /home/luis/docker/kodimedia:/media:ro \
              --privileged \
            -- \
            erichough/kodi
```

But after the x11docker WARNINGs I get some errors before the VDPAU one that can't figure what are about.
```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
```

Anyway even if it worked, using  `--privileged` seems scary enough in a container for kodi.

**Comment by bachulator** [comment] 2020-09-03 19:46
Hi, struggling with the same issue. Any chance the issue would be resolved?

**Comment by lulol** [comment] 2020-09-05 21:36
@bachulator :
- Download the repo. (You just need `Dockerfile` and `entrypoint.sh`)
- `chmod +x entrypoint.sh`
- Add the missing packages to `Dockerfile` as noted by @begicj or apply this patch:
```
--- Dockerfile.orig	2020-08-30 18:01:55.553537291 +0200
+++ Dockerfile	2020-08-30 18:08:12.662272647 +0200
@@ -107,6 +107,8 @@
@@ -107,6 +107,8 @@
                                                              \
     apt-get update                                        && \
     apt-get install -y --no-install-recommends $packages  && \
+    apt-get upgrade -y &&                                    \
+    apt-get install -y i965-va-driver mesa-utils mesa-utils-extra libxv1 && \
     apt-get -y --purge autoremove                         && \
     rm -rf /var/lib/apt/lists/*
```
- Rebuild the image with: `docker build --tag mykodi .`
- Use your `mykodi`image with `x11docker` instead of `erichough/kodi`
- I guess that from now on you need to watch for updates yourself and then do all this process manually again.

So far I've not encountered any issue enabling the hardware-accelerated video since I'm using kodi with these packages included.

**Comment by bachulator** [comment] 2020-09-06 16:42
Hi @lulol.

Thanks for the tip. I think I have succeeded to modify the Dockerfile and build modified image. But to be frank I am not entirely sure that worked out as expected. Load seems to be lower but under codec info for multiple sources I still see SW as rendering method. As addition I don't see any VAAPI options under Settings>Player.  Do you see similar things in your case or did I miss something. Could you please share the X11docker command you are using to launch your newly built image?

Thanks in advance.

**Comment by lulol** [comment] 2020-09-06 19:23
@bachulator I see the VAAPI options under Settings>Player in kodi just fine, and the video decoder uses the hardware acceleration.
![screenshot000](https://user-images.githubusercontent.com/14217781/92333517-56287f80-f086-11ea-9960-49733ff473fa.jpg)
![screenshot001](https://user-images.githubusercontent.com/14217781/92333515-545ebc00-f086-11ea-8045-9a20344c4964.jpg)

Did you used the `--gpu` option with X11docker as well as pointed out by gsantner?

I'm using this with Intel graphics. If that is not your case you may need to [use the package va-driver-all instead of i965-va-driver to get the drivers for AMD and Nvidia](https://github.com/ehough/docker-kodi/issues/17#issuecomment-483867782) as mviereck suggested.

The X11docker command I use is  [a few comments above this](https://github.com/ehough/docker-kodi/issues/17#issuecomment-683759503),  (without the `--privileged`).

**Comment by bachulator** [comment] 2020-09-07 05:28
@lulol 

Hmm. I obviously missing something here. 

Ok. I have intel video since with bare-metal installation I have VAAPI option and decoding is HW based with i965-va-driver .

My DockerFile looks like original except last part
` ...  
   tzdata"                                               && \
                                                             \
    apt-get update                                        && \
    apt-get install -y --no-install-recommends $packages  && \
    apt-get upgrade -y &&                                    \
    apt-get install -y va-driver-all mesa-utils mesa-utils-extra libxv1 && \
    apt-get -y --purge autoremove                         && \
    rm -rf /var/lib/apt/lists/*
...`

I start build and tag process:
`build --tag bachkodi . > build `

Build process finishes successfully and from the logs I do see va drivers installation.  
`Preparing to unpack .../6-va-driver-all_2.1.0-3_amd64.deb ...
Unpacking va-driver-all:amd64 (2.1.0-3) ...
Setting up i965-va-driver:amd64 (2.1.0-0ubuntu1) ...
Setting up mesa-va-drivers:amd64 (20.0.8-0ubuntu1~18.04.1) ...
Setting up libgles2:amd64 (1.0.0-2ubuntu2.3) ...
Setting up libwayland-egl1:amd64 (1.16.0-1ubuntu1.1~18.04.3) ...
Setting up mesa-utils-extra (8.4.0-1) ...
Setting up va-driver-all:amd64 (2.1.0-3) .`

I am X11 user so my kodi start script looks like this, but I am still not gettin
`/usr/bin/x11docker --name="Kodi"  --pulseaudio  --hostnet --gpu  --homedir /home/bach/  bachkodi:latest`

**Comment by lulol** [comment] 2020-09-07 06:52
Did you change to the Expert options in kodi to show the VAAPI options? But anyway by default all should be enabled so that won't limit the hardware decoding.

You may try the `--xorg` and/or `--desktop` options in x11docker, but really I've no clue.

Other than that, I'm sorry that don't know why fails to init the vdp_device in the container since it seems to work in your system. May be others have any idea?

**Comment by bachulator** [comment] 2020-09-07 07:05
@lulol 

I did changed to Expert, and still no options available. 

Will try the --desktop option, to see if that helps, --xorg is not working for me since I am starting the script from running X11 session.

Thanks for support @lulol , hopefully will find the root cause for the issue.

**Comment by bachulator** [comment] 2020-09-07 09:32
To whoever it concerns. I have managed to solve the issue by rebuilding the docker image to the same OS version as host by changing to
`FROM ubuntu:focal`
you will need to change/remove some packages from the Dockerfile sine they might not be available for your OS version.

I suspect the issue was related to different VAAPI version in focal and bionic (1.7.X  vs 1.1) having them on the same version seems to solve the issue.

Cheers,
bachulator

**Comment by mviereck** [comment] 2020-09-07 11:11
> I suspect the issue was related to different VAAPI version in focal and bionic (1.7.X vs 1.1) having them on the same version seems to solve the issue.

Thank you for pointing that out! A hint is added to x11docker wiki.

**Comment by ehough** [comment] 2021-02-23 22:53
[Version 3 of this image is now available](https://github.com/ehough/docker-kodi/releases/tag/v3.0.0). In addition to running on Ubuntu Focal, it also includes the `va-driver-all` package, so everyone (Intel, Nvidia, etc.) should now have out-of-the-box hardware-accelerated video.

Closing this issue, but please feel free to [open up a new issue](https://github.com/ehough/docker-kodi/issues/new) or [post in the discussion forum if](https://github.com/ehough/docker-kodi/discussions) you're still having any trouble.

**Closed by ehough** 2021-02-23 22:53 UTC
Labels: question

**Comment by RobertusIT** [comment] 2021-10-21 16:00
**I have a very weird issue:**

gpu accelleration, works only few seconds, 8 seconds, then stopped working and cpu come up.

Why?

How can i fix it ? from intel_gpu_top i can see render in use and video, but few seconds.
Need a video or this issue is know and there is a fix ?

**Comment by mviereck** [comment] 2022-06-03 07:34
x11docker recently got some fixes for VA-API and VDPAU video decoding support.
Compare https://github.com/mviereck/x11docker/issues/443#issuecomment-1144800334
It turned out that different VA-API versions of host and container seem not to matter. Instead, x11docker has to set some environment variables so the container uses the correct driver files.

Tests reports are appreciated! The fix needs to be tested on several different GPU setups.

This might improve docker-kodi a lot and fix some issues mentioned above.

> [Version 3 of this image is now available](https://github.com/ehough/docker-kodi/releases/tag/v3.0.0). In addition to running on Ubuntu Focal, it also includes the `va-driver-all` package, so everyone (Intel, Nvidia, etc.) should now have out-of-the-box hardware-accelerated video.

It might make sense to add `vdpau-driver-all`, too. VDPAU has the same goal as VA-API, originally they were developed for different GPUs. I am not sure if kodi uses one or the other or might need support of both depending on the GPU.
